# Generated by Django 5.1.6 on 2025-03-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('store_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('inventory_level', models.FloatField()),
                ('units_sold', models.FloatField()),
                ('units_ordered', models.FloatField()),
                ('demand_forecast', models.FloatField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('weather_condition', models.CharField(max_length=100)),
                ('holiday_promotion', models.CharField(max_length=100)),
                ('competitor_pricing', models.FloatField()),
                ('seasonality', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-date', 'store_id', 'product_id'],
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('predicted_sales', models.FloatField()),
                ('actual_sales', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'store_id', 'product_id'],
            },
        ),
    ]
