# Generated by Django 5.1.6 on 2025-03-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='seasonality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
